
# history:
# Deleting all the apps the creates windows using the
# kgws resources.

all: 

# the library.
	make -C libcore
# These apps do not create windows.
	make -C gdeshell

# Clean libcore
	-rm -rf libcore/obj/*.o
clean:
	-rm -rf libcore/obj/*.o
clean-all:
#todo



